apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-argo-eks
  labels:
    app: kubernetes-argo-eks
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubernetes-argo-eks
  template:
    metadata:
      labels:
        app: kubernetes-argo-eks
    spec:
      containers:
        - name: kubernetes-argo-eks
          image: achin16/kubernetes-argo-eks:v1
          ports:
            - containerPort: 80
